### ISSUE TITLE
Each tab is rendered only once

### ISSUE THREAD

**Issue by pichi** [livebook-dev/kino_benchee#6]
I have noticed the weird behavior of tabs. Each tab is rendered only once.
Way to reproduce:

1. Evaluate benchmark
2. Click on the first tab Run Time Statistics - observe the result
3. Click on the second tab Memory Statistics - observe the result
4. Click on the third tab Reduction Statistics - observe the result
5. Click on the first tab Run Time Statistics - there is still content of the third tab

Workaround Click at least once on the icon Amplify output.

https://github.com/livebook-dev/kino_benchee/assets/45734/c754f85c-dba2-4c32-8322-0d1551b93697

**Comment by jonatanklosko** [comment]
This should be fixed on Livebook main :)

**Comment by pichi** [comment]
@jonatanklosko Can you point me to the issue in the Livebook main where this issue is addressed so I can track it down?

**Comment by jonatanklosko** [comment]
See the fix in https://github.com/livebook-dev/livebook/pull/2536 :)

**Comment by pichi** [comment]
Thanks.
